[versions]
kotlin = "2.0.21" # https://github.com/JetBrains/kotlin/releases/latest
junit-jupiter = "5.11.2" # https://github.com/junit-team/junit5/releases

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
